import SwiftUI

/// Lucide (lucide.dev, ISC) replaces SF Symbols app-wide. The SVGs live in
/// Assets.xcassets/lucide as template images, so they tint with
/// `foregroundStyle` like symbols did.
///
/// Lucide is a stroke-only set. Where a solid glyph reads better — rating
/// stars, likes, saved bookmarks — a `-fill` variant is generated by switching
/// the SVG's `fill` from none to currentColor. This only works for glyphs whose
/// silhouette survives being filled: lock, house and book-open turn into blobs,
/// so they stay stroked and colour alone carries their state.
enum Lucide {
    static let bell = "bell"
    static let arrowLeft = "arrow-left"
    static let ban = "ban"
    static let book = "book-open"
    static let bookmark = "bookmark"
    static let bookmarkFill = "bookmark-fill"
    static let camera = "camera"
    static let check = "check"
    static let chevronRight = "chevron-right"
    static let cookingPot = "cooking-pot"
    static let ellipsis = "ellipsis"
    static let externalLink = "external-link"
    static let fileText = "file-text"
    static let flag = "flag"
    static let heart = "heart"
    static let heartFill = "heart-fill"
    static let house = "house"
    static let image = "image"
    static let link = "link"
    static let lock = "lock"
    static let playCircle = "circle-play"
    static let plus = "plus"
    static let search = "search"
    static let settings = "settings"
    static let shield = "shield"
    static let star = "star"
    static let starFill = "star-fill"
    static let user = "user"
    static let userPlus = "user-plus"
    static let utensils = "utensils"
    static let x = "x"
}

/// Drop-in replacement for `Icon()`. Lucide SVGs are 24×24 with no
/// optical sizing, so the frame is set explicitly rather than via `.font`.
struct Icon: View {
    let name: String
    var size: CGFloat = 20

    init(_ name: String, size: CGFloat = 20) {
        self.name = name
        self.size = size
    }

    var body: some View {
        Image(name)
            .renderingMode(.template)
            .resizable()
            .scaledToFit()
            .frame(width: size, height: size)
    }
}
